[package]
name = "rusty_gameboy"
version = "0.1.0"
authors = ["Christo Stephenson <code@christo.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
